apiVersion: v1
kind: Service
metadata:
  namespace: apis
  name: order-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "aksLoadBalancerSubnet"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.2.2.4
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: order-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apis
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: debug
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "64Mi"
          requests:
            cpu: "250m"
            memory: "32Mi"
        image: IMAGE_TAG
        ports:
        - containerPort: 8080
          name: http
      