apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-app1-green-deployment
  namespace: project1
  labels:
    app: project1-app1-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project1-app1-green
  template:
    metadata:
      labels:
        app: project1-app1-green
    spec:
      containers:
      - name: project1-app1-green-container
        image: belstarr/colourserver:dev-0.1.5-863eab5 
        env:
        - name: COLOUR
          value: "green"
        args: ["$(COLOUR)"]
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits: 
            memory: 128Mi
            cpu: "1"
          requests:
            memory: 64Mi
            cpu: "0.5"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-app2-green-deployment
  namespace: project1
  labels:
    app: project1-app2-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project1-app2-green
  template:
    metadata:
      labels:
        app: project1-app2-green
    spec:
      containers:
      - name: project1-app2-green-container
        image: belstarr/colourserver:dev-0.1.5-863eab5 
        env:
        - name: COLOUR
          value: "green"
        args: ["$(COLOUR)"]
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits: 
            memory: 128Mi
            cpu: "1"
          requests:
            memory: 64Mi
            cpu: "0.5"
          
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-app1-blue-deployment
  namespace: project1
  labels:
    app: project1-app1-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project1-app1-blue
  template:
    metadata:
      labels:
        app: project1-app1-blue
    spec:
      containers:
      - name: project1-app1-blue-container
        image: belstarr/colourserver:dev-0.1.5-863eab5 
        env:
        - name: COLOUR
          value: "blue"
        args: ["$(COLOUR)"]
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits: 
            memory: 128Mi
            cpu: "1"
          requests:
            memory: 64Mi
            cpu: "0.5"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-app2-blue-deployment
  namespace: project1
  labels:
    app: project1-app2-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: project1-app2-blue
  template:
    metadata:
      labels:
        app: project1-app2-blue
    spec:
      containers:
      - name: project1-app2-blue-container
        image: belstarr/colourserver:dev-0.1.5-863eab5 
        env:
        - name: COLOUR
          value: "blue"
        args: ["$(COLOUR)"]
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits: 
            memory: 128Mi
            cpu: "1"
          requests:
            memory: 64Mi
            cpu: "0.5"
          
---

apiVersion: v1
kind: Service
metadata:
  name: project1-app1-green-service
  namespace: project1
spec:
  selector:
    app: project1-app1-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: project1-app1-blue-service
  namespace: project1
spec:
  selector:
    app: project1-app1-blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: project1-app2-blue-service
  namespace: project1
spec:
  selector:
    app: project1-app2-blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: project1-app2-green-service
  namespace: project1
spec:
  selector:
    app: project1-app2-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project1-ingress
  namespace: project1
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /project1/app1
        pathType: "Prefix"
        backend:
          service:
            name: project1-app1-blue-service
            port:
              number: 80
      - path: /project1/app2
        pathType: "Prefix"
        backend:
          service:
            name: project1-app2-blue-service
            port:
              number: 80
